### ISSUE TITLE
Admin quiz template create 

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#19]
New card to enter new quiz details:

1. name (input)
2. status (inactive/active) default: inactive
2. Minimum score to pass: input number 
3. Shuffle questions (checkbox)
3. Retry attempts input number
4. Time limit: input number (minutes)

Related: issue: https://github.com/danutchindris/edu-hospice-api/issues/127

**Comment by razvantudorache** [comment]
Route to access the page: /admin/new-quiz/1

**Comment by razvantudorache** [comment]
Issue has been succesfully implemented and integrated with server part. 
Open question: 
- STATUS should be replaced by enabled: boolean = true/false. At this moment because STATUS is ACTIVE / INACTIVE, does not offer the possibility to be translated. On server side STATUS accept only these two options.

**Comment by fnitu** [comment]
Status will be removed from UI.

**Comment by razvantudorache** [comment]
Status field removed
